---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: k8s-deploy
spec:
  replicas: 4
  selector:
     matchLabels:
            app: app-end
  template:
     metadata:
         labels:
            app: app-end
     spec:
       containers:
           - name: ctr123
             image: sitaramreddy/k8s-jenkins-demo:1
  

---
apiVersion: v1
kind: Service
metadata: 
    name: np-service
spec:
    selector:
         app: front-end
    type: NodePort
    ports: 
     - port: 8888
       targetPort: 8888
       nodePort: 30005




























                                                                                                                                                                                                                           
